
path:
  enterprise-costumer: /api/enterprise-customers
  personal-costumer: /api/personal-customers

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/customer_service

#logging:
#  config: K:/bootcamp/proyecto1/customer-service/src/main/resources/logback.xml

server:
  port: 8082